language: java

jdk:
  - oraclejdk8

# build only commits to branch master or where pattern matches "n.n" (where n is a number), e.g. 5.2
branches:
  only:
    - master
    - /^\d+(\.\d+)+$/

#os:
#  - linux
#  - osx

# copy the settings.xml for maven from the "travis" branch
before_install:
# - "git clone -b travis `git config --get remote.origin.url` target/travis"

services:
  - mysql # server:"127.0.0.1"; user:"root"; password:""
  - postgresql "9.6" # server:"127.0.0.1"; user:"postgres"; password:""
  - mongodb #  server:"127.0.0.1" user/pass see below
  - memcached # Memcached uses the default configuration and binds to localhost.

before_install:
  - mysql -e "create database IF NOT EXISTS $MYSQL_DATABASE;" -uroot
  - psql -c "create database $POSTGRE_DATABASE;" -U postgres
  - sleep 15 # necessary for the mongodb command to work because it does not accept intermittent connections
  - mongo test --eval "db.createUser({user:'$MONGODB_USERNAME',pwd:'$MONGODB_PASSWORD',roles:['readWrite']});"
  # - mongo test --eval 'db.addUser("travis", "test");'
  # for more see https://docs.travis-ci.com/user/database-setup


script:
# maven deploy process (builds lucee and deploys to sonatype)
 - mvn -e -f loader/pom.xml clean deploy --settings travis-settings.xml #target/travis/settings.xml

############ increment maven version (not working) ###########
# - mvn --batch-mode -f loader/pom.xml release:update-versions
# - git config --global user.email "${GIT_EMAIL}"
# - git config --global user.name "${GIT_USERNAME}"
# - git config --global user.password "${GIT_PASSWORD}"
# - git add -f loader/pom.xml # add the updated pom
# - git commit -m "update maven version"
# - git remote -v
# - git remote set-url origin https://github.com/lucee/Lucee.git
# - git push origin master

#deploy:
#	skip_cleanup: true

notifications:
  slack: luceeserver:ZTfbu4bVSLFmakRcLInrNZIT
  email:
    - michael@lucee.org
    - igal@lucee.org

after_success:
# - version=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | egrep -v '^\[|Downloading:' | tr -d ' \n')
- curl "http://stable.lucee.org/rest/update/provider/buildLatest"
- curl "http://download.lucee.org/?reset=1"



#- git commit -a -m "Committed by Travis-CI build number: $TRAVIS_JOB_ID "
